config/routes.rb
Rails.application.routes.draw do
  resources :agendamentos
  resources :infos
  resources :empresas
  devise_for :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agendamento.rb
class Agendamento < ApplicationRecord
  belongs_to :empresa
  belongs_to :usuario
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  belongs_to :usuario

  validates :nome, presence: true
end

app/models/info.rb
class Info < ApplicationRecord
  belongs_to :perfil
  belongs_to :usuario

  validates :nome, :endereco, :numero, :bairro, :cidade, presence: true
end

app/models/perfil.rb
class Perfil < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  before_action :set_agendamento, only: [:show, :edit, :update, :destroy]

  # GET /agendamentos
  # GET /agendamentos.json
  def index
    @agendamentos = Agendamento.all
  end

  # GET /agendamentos/1
  # GET /agendamentos/1.json
  def show
  end

  # GET /agendamentos/new
  def new
    @agendamento = Agendamento.new
  end

  # GET /agendamentos/1/edit
  def edit
  end

  # POST /agendamentos
  # POST /agendamentos.json
  def create
    @agendamento = Agendamento.new(agendamento_params)

    respond_to do |format|
      if @agendamento.save
        format.html { redirect_to @agendamento, notice: 'Agendamento was successfully created.' }
        format.json { render :show, status: :created, location: @agendamento }
      else
        format.html { render :new }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendamentos/1
  # PATCH/PUT /agendamentos/1.json
  def update
    respond_to do |format|
      if @agendamento.update(agendamento_params)
        format.html { redirect_to @agendamento, notice: 'Agendamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @agendamento }
      else
        format.html { render :edit }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendamentos/1
  # DELETE /agendamentos/1.json
  def destroy
    @agendamento.destroy
    respond_to do |format|
      format.html { redirect_to agendamentos_url, notice: 'Agendamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agendamento
      @agendamento = Agendamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agendamento_params
      params.require(:agendamento).permit(:empresa_id, :usuario_id, :agendamento)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empresa_params
      params.require(:empresa).permit(:nome, :usuario_id)
    end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  
  def index
    @infos = Info.all
  end

end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/agendamentos/_form.html.erb
<%= form_with(model: agendamento, local: true) do |form| %>
  <% if agendamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agendamento.errors.count, "error") %> prohibited this agendamento from being saved:</h2>

      <ul>
        <% agendamento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :empresa_id %>
    <%= form.text_field :empresa_id %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="field">
    <%= form.label :agendamento %>
    <%= form.datetime_select :agendamento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agendamentos/edit.html.erb
<h1>Editing Agendamento</h1>

<%= render 'form', agendamento: @agendamento %>

<%= link_to 'Show', @agendamento %> |
<%= link_to 'Back', agendamentos_path %>

app/views/agendamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agendamentos</h1>

<table>
  <thead>
    <tr>
      <th>Empresa</th>
      <th>Usuario</th>
      <th>Agendamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agendamentos.each do |agendamento| %>
      <tr>
        <td><%= agendamento.empresa_id %></td>
        <td><%= agendamento.usuario_id %></td>
        <td><%= agendamento.agendamento %></td>
        <td><%= link_to 'Show', agendamento %></td>
        <td><%= link_to 'Edit', edit_agendamento_path(agendamento) %></td>
        <td><%= link_to 'Destroy', agendamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agendamento', new_agendamento_path %>

app/views/agendamentos/new.html.erb
<h1>New Agendamento</h1>

<%= render 'form', agendamento: @agendamento %>

<%= link_to 'Back', agendamentos_path %>

app/views/agendamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa:</strong>
  <%= @agendamento.empresa_id %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @agendamento.usuario_id %>
</p>

<p>
  <strong>Agendamento:</strong>
  <%= @agendamento.agendamento %>
</p>

<%= link_to 'Edit', edit_agendamento_path(@agendamento) %> |
<%= link_to 'Back', agendamentos_path %>

app/views/empresas/_form.html.erb
<%= form_with(model: empresa, local: true) do |form| %>
  <% if empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
        <% empresa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empresas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nome %></td>
        <td><%= empresa.usuario_id %></td>
        <td><%= link_to 'Show', empresa %></td>
        <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @empresa.nome %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @empresa.usuario_id %>
</p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/infos/_form.html.erb
<%= form_with(model: info, local: true) do |form| %>
  <% if info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
        <% info.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :perfil_id %>
    <%= form.text_field :perfil_id %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing Info</h1>

<%= render 'form', info: @info %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Infos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Numero</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Perfil</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.nome %></td>
        <td><%= info.endereco %></td>
        <td><%= info.numero %></td>
        <td><%= info.bairro %></td>
        <td><%= info.cidade %></td>
        <td><%= info.perfil_id %></td>
        <td><%= info.usuario_id %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form', info: @info %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @info.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @info.endereco %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @info.numero %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @info.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @info.cidade %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @info.perfil_id %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @info.usuario_id %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>